 <?php

$conn = new mysqli("localhost", "server", "00000000", "dataset");

$sql = "create table work_std (
   id int(11) primary key auto_increment,
   localtime2 date,
   carType1 varchar(60),
   item_index_no varchar(60),
   itemNo1 varchar(60),
   itemName1 varchar(60),
   machineName1 varchar(60),
   materialName1 varchar(60),
   materialGrade1 varchar(60),
   materialColor1 varchar(60),
   nozzle1 double,
   sHeater1 double,
   sHeater2 double,
   sHeater3 double,
   sHeater4 double,
   nozzle2 double,
   wHeater1 double,
   wHeater2 double,
   wHeater3 double,
   wHeater4 double,
   sMoldTemper1 double,
   wMoldTemper1 double,
   sMoldTemper2 double,
   wMoldTemper2 double,
   sIPressure1 double,
   sIPressure2 double,
   sIPressure3 double,
   sIPressure4 double,
   sIPressure5 double,
   wIPressure1 double,
   wIPressure2 double,
   wIPressure3 double,
   wIPressure4 double,
   wIPressure5 double,
   sISpeed1 double, 
   sISpeed2 double,
   sISpeed3 double,
   sISpeed4 double,
   sISpeed5 double,
   wISpeed1 double, 
   wISpeed2 double,
   wISpeed3 double,
   wISpeed4 double,
   wISpeed5 double,
   sIPosition1 double,
   sIPosition2 double,
   sIPosition3 double,
   sIPosition4 double,
   sIPosition5 double,
   wIPosition1 double,
   wIPosition2 double,
   wIPosition3 double,
   wIPosition4 double,
   wIPosition5 double,
   sGuidePressure1 double,
   sGuidePressure2 double,
   sGuidePressure3 double,
   sGuidePressure4 double,
   sGuidePressure5 double,
   wGuidePressure1 double,
   wGuidePressure2 double,
   wGuidePressure3 double,
   wGuidePressure4 double,
   wGuidePressure5 double,
   sGuideSpeed1 double,
   sGuideSpeed2 double,
   sGuideSpeed3 double,
   sGuideSpeed4 double,
   sGuideSpeed5 double,
   wGuideSpeed1 double,
   wGuideSpeed2 double,
   wGuideSpeed3 double,
   wGuideSpeed4 double,
   wGuideSpeed5 double,
   dryTime2 double,
   dryTemp2 double,
   meterage1 double,
   cushion1 double,
   InjectionTime1 double,
   guideTime1 double,
   dryTemp1 double,
   dryTime1 double,
   moldPreHeat1 double,
   moldPreHeat2 double,
   preShot1 double,
   revision1 varchar(60),
   revisionDate1 varchar(60),
   revisionReason1 varchar(60),
   acc1 varchar(60),
   acc2 varchar(60),
   acc3 varchar(60)
   )";
$res = mysqli_query($conn, $sql);		// 테이블 생성

echo $res;

mysqli_close($conn); // 종료

?>

생성완료